- resources/views/uiobjects/menu/typeSelect.blade.php
image url 에 asset 함수로 감쌈
* 하위 디렉토리에 XE3 설치시 메뉴 추가 화면에서 type들의 썸네일이 나오지 않는 문제*
*썸네일 (screenshot) URL을 출력할 때 asset 함수로 감쌈*
> 하위 디렉토리에 설치시에 메뉴 추가시 type 들의 썸네일 안나오는 문제 해결

- core/src/Xpressengine/Media/Handlers/ImageHandler.php
- core/src/Xpressengine/Media/MediaManager.php
- core/src/Xpressengine/Storage/FilesystemHandler.php
- core/src/Xpressengine/Storage/Storage.php
- `XeStorage::upload();`를 사용하여 이미지를 aws s3 에 업로드하면 private 상태로 업로드 됩니다.
- `XeMedia::createThumbnails();`를 사용하여 썸네일을 생성하여 업로드하면 private 상태로 업로드 됩니다. 
`XeStorage::upload()` 또는` XeMedia::createThumbnails()` 에서 이미지를 생성하거나 만들면 `\Illuminate\Contracts\Filesystem\Filesystem` 의 메소드 중 하나인 `put` 메소드 의 매개 변수 중 $option 값이 기본값으로 지정되어서 문제입니다.
- `XeStorage::upload()` 와 `XeMedia::createThumbnails()` 에서 `\Illuminate\Contracts\Filesystem\Filesystem` 에 있는  `put` 메소드의 매개변수 $option 값을 설정할 수 있도록 하였습니다.
- `XeMedia::createThumbnails()` 에서 파일 드라이버 (local, s3 등)를 선택할 수 있도록 하였습니다.
> 'XeStorage::upload() 가 Storage::put() 의 매개변수 $option 을 변경할 수 있도록 수정

- resources/assets/core/media_library/vue/app.vue
로그인한 계정 권한(super)에 따라 미디어 라이브러리의 UI가 깨집니다.
미디어 라이브러리 vue 파일에서 `media-library-layer-popup--sidebar` CSS 클래스를 `$root.user.rating === 'super'` 조건에 따라 추가하고 있습니다.
fix #1100
> fix(media_library): 미디어 라이브러리 파일 업로드 UI 오류 수정

- resources/views/install/index.blade.php
암호로 사용가능한 글자를 확인한다.
영문문자, 특수문자 만 입력 가능하도록 체크 한다.
Issue #1090 에서 자세한 설명을 적어두었습니다.
암호의 문자로 한글이 들어가는 문제가 발생되어 암호로 사용가능한 문자를 체크 합니다.
암호로 한글이 들어가기 때문에 설치시 혼선이 생기는 경우가 발생하였습니다.
암호로 영문자, 특수문자를 제외한 다른 문자가 들어간 것을 체크하도록 하였습니다.
> 암호에 적합한 글자를 확인한다.

- app/Console/Commands/CharsetConvert.php
- app/Console/Kernel.php
이모지 지원 등의 문제로 데이터베이스의 charset을 `utf8mb4`로 지정할 필요가 있을 경우, 사용자의 선택에 따라 데이터베이스 문자셋을 변경할 수 있도록 하는 커밋입니다. resolve #1102 
https://github.com/xpressengine/xpressengine/blob/3c95b0d2ada9157174af56ff374adc067809cfbc/app/Console/Commands/XeInstall.php#L503-L504
XpressEngine을 설치하기 전이라면 위 두 줄을 `utf8mb4`로 바꾸고 설치를 진행하는 것으로 설정을 완료할 수 있지만, 이미 서비스 중인 사이트에서도 데이터베이스와 테이블의 문자셋을 변경할 수 있는 artisan 명령어를 추가했습니다.
데이터베이스와 테이블의 charset을 변경하고 나서 `config/production/database.php` 설정도 바꿔주어야 하는데, 혹시 라라벨 내에서 자동으로 변경할 수 있는 방법이 있을까 찾아보다가 우선 config 파일은 수동으로 수정하는 방향으로 가정하고 진행했습니다.
> feat(commands): 데이터베이스 charset 변환 artisan 명령어 추가

- core/src/Xpressengine/Settings/SettingsMiddleware.php
1. 새로운사용자를 '관리자' 등급으로 생성
2. [설정]-[관리자페이지 권한 설정] 메뉴에서 '회원목록 접근' 권한과 '회원정보 수정' 권한을 '관리자' 등급으로 지정
3. 해당 사용자로 로그인하여 회원목록에 접근
4. 권한이 없다고 나옴
permission id가 없는 모든 settings route에 접근할때 SettingsMiddleware에서 튕겨지게 되어있었습니다.
https://github.com/xpressengine/xpressengine/blob/3c95b0d2ada9157174af56ff374adc067809cfbc/core/src/Xpressengine/Settings/SettingsMiddleware.php#L117-L121
회원목록에 접근할때 관리자패스워드 확인을 위해 settings.auth.admin 라우트로 redirect되게 되어있는데, 문제는 이 라우트에 permission id가 부여되어있지 않다는 것입니다.
https://github.com/xpressengine/xpressengine/blob/3c95b0d2ada9157174af56ff374adc067809cfbc/routes/web.php#L503-L506
permission id가 부여되어있지 않은 라우트는 보안정책을 적용하지 않겠다는 뜻으로 받아들이고 접근을 허용하고, permission id가 있는경우에는 권한을 검사하도록 수정했습니다.
> (Issue #1114) 최고관리자가 아닌 사용자가 회원관리페이지 접근시 발생하는 에러 해결

- app/Http/Controllers/ArtisanBackgroundHelper.php
1. 윈도우10, php 7.3환경 cmd에서 `php -S 127.0.0.1:80`로 빌트인서버 구동 (다른버전도 마찬가지 일겁니다)
2. 브라우저를 통해 관리자페이지 접속후 플러그인 업데이트 버튼 클릭
3. 컴퓨터에 cmd창이 자동으로 열리며 아래와 같은 에러 발생
https://github.com/xpressengine/xpressengine/blob/bcc670989de39a1067dd344e720e30e38fbaa4e8/app/Http/Controllers/ArtisanBackgroundHelper.php#L111
ArtisanBackgroundHelper.php에서 호출하는 `new Process()->run()` 함수는 php의 내장함수 `proc_open`을 호출하는데, 이때 윈도우의 경우 env값이 존재하지 않아 DB커넥션 정보를 읽어오지 못해 접속불가한것으로 추정.
아래는 힌트를 얻게된 Stackoverflow 글
https://stackoverflow.com/a/32976189
`new Process()->run()` 호출시 php내장함수 `getenv()`를 이용해 env값을 넘겨주도록 수정. (해결됨)
> 윈도우환경에서 컨트롤러 통해 플러그인 업데이트시 발생하는 getaddrinfo 에러 해결

- app/Providers/DatabaseServiceProvider.php
1. app.debug = true로 설정
2. 모델에 $dates Mutator 추가
3. 모델 저장
4. 에러
#1158 
DatabaseServiceProvider에서 $binding을 string으로 변환할때 DateTime인 경우도 처리할 수 있게 if문 추가
> (디버깅모드일때) Object of class DateTime could not be converted to string 에러 해결

- core/src/Xpressengine/Foundation/ReleaseProvider.php
1. 윈도우에서 CMD로 php artisan xe:update 실행
2. 업데이트 안됨 (버전 인식 불가)
*어떤게 원인 이었나요?*
윈도우에서 PHP_EOL로 explode 하는 함수가 작동하지 않았고, PHP_EOL과 버전정보문서(versions.txt)간의 new line 문자가 다른 것으로 추정
*어떤걸 수정했나요?*
윈도우 리눅스 양쪽에서 호환되도록 PHP_EOL 을 \n으로 변경하는 대신 array_map("rtrim"으로 윈도우 new line 문자들을 제거
(Stackoverflow 참고함 https://stackoverflow.com/questions/4975411/when-do-i-use-php-eol-instead-of-n-and-vice-versa-ajax-jquery-client-problem)
> 윈도우 환경에서 artisan xe:update 실행시 버전인식 못하는 문제 해결

- app/Console/Commands/PrivateUpdateCommand.php
- core/src/Xpressengine/Plugin/PluginEntity.php
1. 윈도우 환경에서 `php artisan private:update XXXX` 실행
2. `The plugin[XXXX] is not private plugin` 에러 발생
3. 2번을 해결해도
```
Unlink plugin
- Unlinking ... Cannot create a file when that file already exists.
In PrivateUpdateCommand.php line 68:
Unable to unlink.  
```
에러 발생
`isPrivate()`은 PHP내장함수 `is_link()`를 기반하여 만들어져 있는데, 윈도우에서 private 플러그인설치시 심볼릭 링크가 아닌 `JUNCTION` 으로 폴더가 만들어집니다.
이 경우 항상 `is_link()`가 `false`를 리턴하기 때문에 에러가 발생합니다.
Unlink 프로세스에서도 Junction에 대한 삭제를 지원하지 않기 때문에 에러가 발생합니다.
https://github.com/xpressengine/xpressengine/blob/703293b425ff739e10b900977a17073416e5c258/core/src/Xpressengine/Plugin/PluginEntity.php#L789-L797
*어떤걸 수정했나요?*
Composer FileSystem 유틸에 있는 함수들을 이용하여 Junction도 인식 & 삭제 가능하도록 변경하였습니다.
> 윈도우에서 private:update 명령 실행시 발생하는 에러 해결 (Junction 호환성 추가)

- core/src/Xpressengine/Plugin/PluginHandler.php
1. XXXX 플러그인 composer.json의 require 필드에 `ext-json: *` 추가
2. `php artisan private:update XXXX` 실행
3. 에러 발생
```
The system cannot find the file specified.
In PluginHandler.php line 339:
Undefined offset: 1  
```
*어떤게 원인 이었나요?*
`getDependencies()`에서 explode시 `ext-json`은 vendor가 없기 때문에 index 1이 존재하지 않아 발생하는 에러입니다.
https://github.com/xpressengine/xpressengine/blob/703293b425ff739e10b900977a17073416e5c258/core/src/Xpressengine/Plugin/PluginHandler.php#L339
*어떤걸 수정했나요?*
어차피 vendor이름은 사용하지 않고 있어서 아래 코드로 대체하였습니다. 
```php
$id = array_last(explode('/', $dependency));
```
> 플러그인에 vendor가 없는 dependency(ext-json)를 추가하면 update 안되는 버그 해결

- app/UIObjects/Form/FormSelect.php
1. FormSelect 사용시 mutiple 옵션을 주고, value를 배열로 넘김
2. value를 인식하지 못해 select되지 않음
value를 === 으로 비교하기 때문에 배열값은 인식 불가함
=== 비교 대신 value를 array로 캐스팅하여 in_array로 체크하도록 함
> FormSelect에서 multiple 옵션 사용시 value가 인식되지 않는 버그 해결

- app/Console/Commands/PluginActivate.php
- app/Console/Kernel.php
https://www.xpressengine.com/forum/php-artisan-%EB%AA%85%EB%A0%B9%EC%96%B4%EB%A1%9C-%ED%94%8C%EB%9F%AC%EA%B7%B8%EC%9D%B8-activation-%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95%EC%9D%B4-%EC%9E%88%EB%82%98%EC%9A%94
포럼에 질문으로 올렸었는데, 컨트롤러에 있는 activate 기능 참고하여 간단하게 구현해봤습니다.
플러그인 활성화때 private 플러그인은 가끔 composer update를 같이해서 timeout 에러가 빈번합니다.
cli 환경에서는 timeout 에러가 없기 때문에, 이런 작업은 주로 artisan 명령어로 하는데 activation 명령어는 없는것 같아 만들어봤습니다.
> plugin:activate 명령어 추가

- example.xe3-nginx-rewrite.conf
1. nginx설정을 서버에 넣고 실행
2. 메인화면에 Together테마 아이콘이 보이지 않음 (폰트파일을 읽어오는 대신 Laravel로 라우팅됨)
1. 샘플로 제공된 nginx 설정이 문제였음... (시간 많이 썼습니다...ㅠ)
https://github.com/xpressengine/xpressengine/blob/5d09e1a1eace9f3f4006c2e49765c72ff9d3c445/example.xe3-nginx-rewrite.conf#L19-L21
위 문법은 인식되지 않고, 아래처럼 해야 인식됨 (Stackoverflow참조)
https://stackoverflow.com/questions/35320674/how-can-i-have-same-rule-for-two-locations-in-nginx-config
```
location ~ ^/(assets|plugins|storage/app/public)/ {
try_files $uri /index.php?$args;
}
```
변경된 룰의 검증이 필요하시다면, nginx 룰 테스트 사이트에서 검증해보실수 있습니다.
https://nginx.viraptor.info/
위에 적었습니다.
추가적으로, `.well-known` 룰도 중복되어 하나는 제거하였습니다. (검증완료)
> nginx에서 plugins폴더 아래 파일을 가져올수 없는 버그 해결 (index.php로 rewrite됨)

- app/Console/Commands/XeInstall.php
<https://github.com/xpressengine/xpressengine/pull/1120#issuecomment-608196687> @akasima 님의 아이디어를 참고해서 기능을 추가했습니다.
`php artisan xe:install` 명령어로 설치하는 과정에서 `utf8`과 `utf8mb4` 중 선택하는 절차를 추가했습니다. <https://github.com/xpressengine/xpressengine/issues/977#issuecomment-495459155> 문제를 고려해서 기본값은 `utf8`으로 뒀습니다.
> feat(xeinstall): 설치할 때 charset 선택 과정 추가

- migrations/PluginMigration.php
이슈  #1124 해결용
1. XE를 설치합니다.
2. `php artisan make:plugin name vendor`를 실행합니다.
3. COMPOSER_HOME 에러발생
COMPOSER_HOME 기본값이 없습니다.
COMPOSER_HOME 기본값을 넣어주었습니다.
> XE설치시 COMPOSER_HOME 값을 storage/framework/.composer 로 기본설정

- app/UIObjects/Form/FormSelect.php
현재 FormSelect UIO에 optgroup을 사용할수 있는 방법이 없음
FormSelect에 optgroups 라는 옵션을 받아올수 있도록 구현
> FormSelect에 optgroups 구현

- core/src/Xpressengine/Presenter/Html/Tags/AttributeTrait.php
- core/src/Xpressengine/Presenter/Html/Tags/JSFile.php
`AttributeTrait` 의 `attr` 메서드를 사용해도 충분하지만 저 또한 해당 메서드들이 있으면 더 직관적일 것 같아  `defer`, `async` 메서드를 추가했습니다.
- `attr`의 값이 있을 때만 속성 값을 넣도록 변경
- `defer()`, `async()` 메서드 추가
> (Issue #1407) defer, async 메서드 추가

- core/src/Xpressengine/Counter/Models/CounterLog.php
- core/src/Xpressengine/Document/Models/Document.php
- core/src/Xpressengine/Document/Models/Revision.php
- core/src/Xpressengine/Log/Models/Log.php
- core/src/Xpressengine/MediaLibrary/Models/MediaLibraryFile.php
- core/src/Xpressengine/Site/Site.php
- core/src/Xpressengine/Storage/File.php
- core/src/Xpressengine/Tag/Tag.php
- core/src/Xpressengine/User/Models/Term.php
- core/src/Xpressengine/User/Models/User.php
- core/src/Xpressengine/User/Models/UserAccount.php
- core/src/Xpressengine/User/Models/UserEmail.php
- core/src/Xpressengine/User/Models/UserGroup.php
- core/src/Xpressengine/User/Models/UserTermAgree.php
- core/src/Xpressengine/Widget/Models/WidgetBox.php
- core/src/Xpressengine/Widget/Models/WidgetBoxHistory.php
라라벨 버전 6.x 부터 모델의 기본키가 정수가 아닌 경우에는 모델에 상속된 $keyType 프로퍼에 ‘string’ 값을 입력해줘야 합니다.
$keyType 프로퍼티가 올바르지 못하는 경우, 관계 사용 시 잘못된 결과물을 반환해줄 수 있습니다.
> [laravel 6.x] Model - keyType

- core/src/Xpressengine/User/Models/Guest.php
- core/src/Xpressengine/User/Models/UnknownUser.php
- core/src/Xpressengine/User/Models/User.php
- core/src/Xpressengine/User/UserInterface.php
유저 조회시 유저와 연관된 약관 동의 여부를 조회하거나, 수정하기 위해, relation을 사용할 수 없었습니다.
유저 모델에 `UserTermAgree` 모델과 연관된 relation이 존재하지 않았습니다.
- `User` 모델에 `agreedTerms` 관계를 추가했습니다.
- `UserInterface` 인터페이스에 `getAgreedTerms` 메소드를 추가하고, `User`,`Guest`, `UnKnownUser`에 각각 구현부를 추가했습니다.
> #1501 유저 모델에서 유저 약관 동의 relation이 존재하지 않는 이슈

- app/Console/Kernel.php
plugin 상에서 `schedule` 을 등록시켜준 후, crontab 을 통해 실행시켜줄때, 두번씩 실행되는 이슈가 있습니다.
커널(`app/Console/Kernel.php`)상에서 `scheduledPlugins` 에 플러그인 적재 시, 플러그인이 두번씩 적재되는 이슈가 있었습니다.
`scheduledPlugins`에 플러그인을 넣을때, 이미 적재가 되었다면, 적재가 되지 않도록 조건문을 추가했습니다.
> #1511 플러그인 상에서 커맨드를 실행하는 scedule을 생성해주고, 크론으로 schedule 실행시 커맨드가 두번 실행되는 이슈
